manifest = "3ecdedd664f9fbc48d46d9676b83e69a196a4b8000bda633d3d401187d463d72"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
target = "//:functional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.48.0" ]
revision = "114bca7424a5da83e30dc8289569039c32a96a27"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.48.0" ]
revision = "f2a3d12da550aca457374033ba38554ccb3b06df"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.48.0" ]
revision = "4298a8c284c634b14e57645296da02636908c57d"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.48.0" ]
revision = "091a74df0877ca3bacd25f50ebdfa23a63dcf4cf"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.48.0" ]
revision = "ba63ae378a5db6dd9a6bb72a19a641670bc60a63"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.48.0" ]
revision = "fd12160efea52b1c40c86cd1b2d10d79f8338ded"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.48.0" ]
revision = "b9ccc9250df2e0328463466c3855dae33a1b35c3"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.48.0" ]
revision = "26a10cdeb43f4b55ad9f8897c89fb289b8c17d84"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.48.0" ]
revision = "5c11da0c08b834b0ad4a20419c839d04b0b4e625"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.48.0" ]
revision = "7720d49d2db36706bd72f52ced20dcc0b328ed08"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.48.0" ]
revision = "8e7647a0fcf5d26c7b5ac6b479d4a656df79ba2b"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.48.0" ]
revision = "4c1501769e93fc95215fcf9c60d74f8fd217f3ab"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.48.0" ]
revision = "e96ba8537c2fc4db905d0edb640d9f9fbf6c275d"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.48.0" ]
revision = "27120861a6c715ce0e09c2e9ca6456afef5eb5c0"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.48.0" ]
revision = "b754127b1ce914967306ff09411e8922bb1a7931"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.48.0" ]
revision = "fd4c61f8e968d62e1d19a11a829a03db600328a9"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.48.0" ]
revision = "ee9cacf3d7ecdef21f84300597bf92739eca2530"
