manifest = "e80eda6164b2bb5378d027c2988a11be651682e06a285f1d99697b00235029eb"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-functional"
target = "//:functional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-tuple"
target = "//:tuple"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.52.0" ]
revision = "d2db9edc46ccdf58e86d82ea9021abe62b1fab0b"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.52.0" ]
revision = "2d6255b8fbd2eec649008975648d95311f698d21"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.52.0" ]
revision = "572e0c8a71b21f0565676a3d4ff91814a8407027"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.52.0" ]
revision = "8c48422f180b40f40b628164fb851349d57f3dc1"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.52.0" ]
revision = "c31e05d0f3a1745b6305e2fa2bf6f78067c9283a"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.52.0" ]
revision = "b59839df5f163ce062737032cfa93542296675f7"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.52.0" ]
revision = "f566a486b9c9670bfe5e14d08eaf06f56ad0e511"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.52.0" ]
revision = "b26612245d8461fdf35482e38a52d3bba582ac59"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.52.0" ]
revision = "bbd74353a180d11588e21da34f824a43c7e5e402"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.52.0" ]
revision = "65b45d0d8119ed37a4829f29677e432d6a36b86c"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.52.0" ]
revision = "ea40e662719516c48040e643b3083c7776941ab6"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.52.0" ]
revision = "15edf9128ec0daaf34f92064585fe4d870897493"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.52.0" ]
revision = "5f6617c1b40228007ca57d7f3b011801fe0f6002"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.52.0" ]
revision = "e44f22f13d3047df7b3302f6f86164593181155d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.52.0" ]
revision = "f3e4e9ce56b3553e90055579e84c1b0738dbb25c"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.52.0" ]
revision = "c1cc7f79c391b2c09a59b13e8aff88a0b25c06a3"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.52.0" ]
revision = "8e193c2456cce1bd79c1525f2d1066b142bf9936"
